---
- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes

- name: Install Server Basics
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - ntp
    - wget
    - curl
    - vim
    - ack-grep
    - git
    - unzip
    - htop
    - tmux
  notify:
    - Start NTP